name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish-updated-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to Container Registry
      if: github.repository_owner == 'maiqueb'
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push container image
      if: github.repository_owner == 'maiqueb'
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/new-cni-verbs:latest
        file: images/postgres.Dockerfile
